classDiagram
    Dispositivo o-- Cliente 
    Medicion o-- Dispositivo
    Notificacion o-- Dispositivo
    Falta o-- Dispositivo

    class Cliente {
    +Email : string
    +Nombre: string
    +Apellido: string
    +Contraseña: string
    +Dispositivos: Dispositivos 
    +Nacimiento: date
    }
    

    class Dispositivo{
    IdDispositivo: int   
    NumSerie: string
    Modelo: string
    Dispositivo: Mediciones
    Notificaciones: Notificacion
    Faltas: Faltas
    }
    

    class Falta
    Falta: IdDispositivo
    Falta: Mensaje

    class Medicion 
    Medicion: IdDispositivo
    Medicion: Unidad
    Medicion: Valor
    Medicion: FechaHora

    class Notificacion
    Notificacion: IdDispositivo
    Notificacion: Mensaje
    Notificacion: FechaHora